[SERVERS]
REQUEST_TIMEOUT = 30
MASTER_URL = http://localhost:2342
TRAVEL_URL = http://localhost:2343
USERNAME = admin
MAX_ATTEMPTS = 5

[PATHS]
# Absolute paths to physical directories
# MASTER ORIGINALS To find Primary images not in sidecar:
MASTER_ORIGINALS = /Volumes/PathTo/MasterOriginals
# MASTER PhotoPrism Compose directory:
MASTER_BASE = /Volumes/PathTo/myMASTERphotoprism/
# MASTER PhotPrism Sidecar directory:
MASTER_SIDECAR = /Volumes/PathTo/myMASTERphotoprism/storage/sidecar

# TRAVEL PhotoPrism Compose directory:
TRAVEL_BASE = /Volumes/PathTo/myTRAVELphotoprism/
# TRAVEL JPEG ORIGINALS directory:
TRAVEL_ORIGINALS = /Volumes/PathTo/mySmallOriginals
# TRAVEL SENTINEL in TRAVEL_ORIGINALS directory:
TRAVEL_SENTINEL = TRAVEL_ORIGINALS/.travelsync_target
# Need user action: create empty file .travelsync_target at TRAVEL_ORIGINALS
# This is a safety measure to keep your MATER Originals safe.

# For YAML Audit:
TRAVEL_SIDECAR = /Volumes/PathTo/myTRAVELphotoprism/storage/sidecar
    
[RESIZE]
MAX_SIZE = 1920
JPEG_QUALITY = 55
ENGINE = sips
# Options: pillow, magick, sips (MacOS)
RJOBS = 2
# As many as user hardware permits
[GLOBAL]
FORCEDEBUGJOB1 = 1
# Forces no parallel work when sync or audit to keep logs organized
# 1 enable 0 disable
JOBS = 2
# [WARNING] Connection pool is full, discarding connection: localhost. Connection pool size: 10
# This is MariaDB and 12 workers. We need to stay well under 10.
# ! 7 maxes out 10 CPUs on Photoprism and DB containers when many items syncing with API PUT
# ! 1 worker if SQLite on any DB; it cannot handle more reliably.
